-- Four new event/service types for the Services section booking flow.
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'ANNIVERSARY';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'FAMILY_CELEBRATION';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'PRODUCT_LAUNCH';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'HOLIDAY_CELEBRATION';
